# Generated by Django 3.2.9 on 2023-03-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('osra_name', models.CharField(max_length=500)),
                ('osra_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shamas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shamas_name', models.CharField(max_length=500)),
                ('osra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.osra')),
            ],
        ),
    ]
