# Generated by Django 3.2.9 on 2023-03-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osra',
            name='osra_id',
        ),
    ]
