# Generated by Django 3.2.9 on 2023-03-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_osra_osra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shamas',
            name='osra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.osra'),
        ),
    ]
