# Generated by Django 3.2.9 on 2023-03-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230325_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shamas',
            name='osra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.osra'),
        ),
    ]
