# Generated by Django 3.2.9 on 2023-03-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shamas_osra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shamas',
            new_name='Shamasa',
        ),
    ]
