# Generated by Django 3.2.9 on 2023-03-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_shamas_shamasa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shamasa',
        ),
    ]
