# Generated by Django 3.2.9 on 2023-03-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_shamasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shamas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shamas_name', models.CharField(max_length=500)),
                ('osra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osra_name', to='api.osra')),
            ],
        ),
    ]
