# Generated by Django 3.2.9 on 2023-03-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230325_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osra_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Shamas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shamas_name', models.CharField(max_length=500)),
                ('osra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.osra')),
            ],
        ),
        migrations.RemoveField(
            model_name='emp',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
