# Generated by Django 3.2.9 on 2023-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230325_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='osra',
            name='osra_id',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
