# Generated by Django 4.1.7 on 2023-04-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230325_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osra',
            old_name='osra_id',
            new_name='osra_number',
        ),
        migrations.RenameField(
            model_name='shamas',
            old_name='osra',
            new_name='osra_number',
        ),
        migrations.AlterField(
            model_name='osra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
