# Generated by Django 4.1.7 on 2023-04-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_osra_id_osra_osra_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shamas',
            old_name='osra_number',
            new_name='osra',
        ),
    ]
