# Generated by Django 4.1.7 on 2023-04-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_osra_number_shamas_osra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osra',
            name='osra_number',
            field=models.IntegerField(unique=True),
        ),
    ]
