# Generated by Django 4.1.7 on 2023-04-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_osra_shamas_osra_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shamas',
            old_name='osra_id',
            new_name='osra',
        ),
    ]
